FROM alpine

MAINTAINER Bill Harris (https://github.com/SDShooter)

RUN apk update && \
  apk add --no-cache snort && \
  apk add --no-cache ca-certificates wget && \             
  update-ca-certificates && \   
  apk add --no-cache --update openssl
  
RUN wget https://www.snort.org/rules/community && \                                                                                                                                                                                                          
  tar -xzvf ./community -C /etc/snort

RUN wget https://www.snort.org/documents/classification-config && \
 	mkdir /var/lib/snort/etc && \
    mv ./classification-config /etc/snort/community-rules/classification.config

RUN wget https://www.snort.org/documents/reference-config && \
    mv ./reference-config /etc/snort/community-rules/reference.config

RUN wget https://github.com/SDShooter/docker-snort-ids/raw/master/rules.tar.gz && \
	mkdir /etc/snort/rules/ && \
	tar -xzvf ./rules.tar.gz -C /etc/snort/rules/

#RUN wget https://www.snort.org/downloads/community/community-rules.tar.gz && \	
#tar -xzv ./community-rules.tar.gz -C /etc/snort/rules/ 
#RUN cat /etc/snort/rules/community-rules/community.rules
RUN rm -f /tmp/* /etc/apk/cache/* ./community ./community-rules.tar.gz
	
RUN find / -name  "threshold.*"
  
#Symlink some files
RUN ln -s /usr/lib/snort_dynamicpreprocessor/ /usr/local/lib/ && \   
	ln -s /usr/lib/snort_dynamicengine/ /usr/local/lib/ && \
	ln -s /usr/lib/snort_dynamicrules/ /usr/local/lib/ 

RUN ls -al /var/lib/snort/etc/threshold.config
#RUN ln
#RUN ls -al /var/lib/snort/
#/etc/snort/reference.config -> /var/lib/snort/etc/reference.config

#etc/snort/community-rules/classification.config requested
#/etc/snort/community-rules/classification.config is a symlink pointing to /var/lib/snort/etc/classification.config
#/etc/snort/classification.config is a symlink to /var/lib/snort/etc/classification.config (which doesn't yet exist)
#/etc/snort/classification.config the real file
#RUN cat /etc/snort/community-rules/classification.config
#RUN cat /etc/snort/community-rules/snort.conf
#RUN ls -al /etc/snort/

ENTRYPOINT ["snort"]
CMD ["--help"]